config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :pins
  resources :customers
  resources :packages
  resources :products
  resources :sales

  get 'about' => "pages#about"
  get 'splashnav' => "pages#splashnav"
  get 'customer' => "customers#index"
  get 'addcustomer' => "customers/add"
  get "product" => "products#index"
  get "pacakge" => "packages#index"
  get "sale" => "sales#index"
  get "pin" => "pins#index"
  root 'pages#splashnav'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	# Relationships
	has_many :sales
	has_many :packages, through: :sales
	has_many :products, through: :packages
	# Validation
	validates :name, :presence => true, :uniqueness => true
	validates :company_name, :presence => true
	validates :customer_id, :presence => true, :uniqueness => true, :numericality => true, :inclusion => 1000..1999
end

app/models/package.rb
class Package < ActiveRecord::Base
	# Relationships
	belongs_to :product
	has_many :sales
	has_many :customers, through: :sales
	# Validations
	validates :package_id, :presence => true, :uniqueness => true, :numericality => true, :inclusion => 3000..3999
	validates :product_id, :presence => true, :numericality => true
	validates :cost, :presence => true, :numericality => true
	# Scopes
	scope :with_product, lambda {|productVar| where(:product_id => productVar )}
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :myimage, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates :myimage, presence: true
	validates :description, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	# Relationships
	has_many :packages
	has_many :sales, through: :packages
	has_many :customers, through: :sales
	# Validation
	validates :product_name, :presence => true, :uniqueness => true
	validates :product_info, :presence => true
	validates :product_base_cost, :presence => true, :numericality => true
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	# Relationships
	belongs_to :customer
	belongs_to :package
	# Validation
	validates :transaction_id, :presence => true, :uniqueness => true, :numericality => true, :inclusion => 5000..5999
	validates :customer_id, :presence => true, :numericality => true
	validates :package_id, :presence => true, :numericality => true
	# Scopes
	scope :with_package, lambda {|packageVar| where(:package_id => packageVar )}
	scope :with_customer, lambda {|customerVar| where(:customer_id => customerVar )}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.all
	end

	def show
		@customer = Customer.find(params[:id])
		@sales = Sale.all
		@packages = Package.all
	end

	def new
    	@customer = Customer.new
  	end

  	def create
  		@customer = Customer.new(params[:customer].permit(:name, :company_name, :customer_id))
  		if @customer.save
  			redirect_to @customer
  		else
  			flash.now[:notice] = "invalid input"
  			render :new
  		end
  	end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
	def index
		@packages = Package.all
	end

	def show
		@package = Package.find(params[:id])
		@sales = Sale.all
		@packages = Package.all
	end

	def new
    	@package = Package.new
  	end

  	def create
  		@package = Package.new(params[:package].permit(:package_id, :product_id, :cost ))
  		if @package.save
  			redirect_to @package
  		else
  			flash.now[:notice] = "invalid input"
  			render :new
  		end
  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def splahnav
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin, you pin head." if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :myimage)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		@sales = Sale.all
	end

	def new
    	@product = Product.new
  	end

  	def create
  		@product = Product.new(params[:product].permit(:product_name, :product_info, :product_base_cost))
  		if @product.save
  			redirect_to @product
  		else
  			render :new
  			flash.now[:notice] = "invalid input"
  		end
  	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	def index
		@sales = Sale.all
	end

	def show
		@sale = Sale.find(params[:id])
		@sales = Sale.all
		@packages = Package.all
		@customers = Customer.all
		@products = Product.all
	end

	def new
    	@sale = Sale.new
  	end

  	def create
  		@sale = Sale.new(params[:sale].permit(:transaction_id, :customer_id, :package_id))
  		if @sale.save
  			redirect_to @sale
  		else
  			render :new
  			flash.now[:notice] = "invalid input"
  		end
  			
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/customers/index.html.erb
<h1> Customers: drag and drop, list elements (non persistant 4 now) </h1>
<%-# Drag and dropable list -%>
<ul id="customerIndex">
	<% @customers.each do |customer| %>
	<%= content_tag_for :li, customer do %>
	<%= link_to customer.name, customer %></li>
	<% end %>
	<% end %>
</ul>
<%-# Link to new customer page -%>
<%= link_to new_customer_path  do %>
<span class="glyphicon glyphicon-plus"></span> New Customer
<% end %>
<br><br>
<p>Calculations:</p>
<%-# Calculate and display total # of customers -%>
<p> Total # of customers: <%= @customers.each.count %> </P>
<%-# Calculate and display total # of sales to all customers -%>
<% @totalSalesNumber = 0 %>
<% @customers.each do |salesVar| %>
<% @totalSalesNumber = @totalSalesNumber + salesVar.sales.count %>
<% end %>
<p> Total # of sales to all customers: <%= @totalSalesNumber %> </P>

app/views/customers/show.html.erb
<h1> Show page for customer</h1>
<%-# Info on selected customer -%>
<table>
<tbody>
<tr>
	<th> Customer Name </th>
	<th> Company Name</th>
	<th> Customer ID</th>
</tr>
<tr>
	<td><%= @customer.name %></td>
	<td><%= @customer.company_name %></td>
	<td><%= @customer.customer_id %></td>
</tr>
</tbody>
</table>
<%-# link back to index page -%>
<%= link_to "All Customers", customers_path %>
<br><br>
<%-# shows # of sales to customer -%>
<p>Number of Sales to this customer: <%= @customer.sales.count %></p>
<%-# shows # of packages bought by this customer -%>
<p>Number of packages sold to this customer: <%= @customer.packages.all.uniq.pluck(:id).count %></p>
<%-# shows # of prodcuts bought by this customer -%>
<p>Number of products sold to this customer: <%= @customer.products.all.uniq.pluck(:id).count %></p>
<%-# Array of sales to customer -%>
<% @touse = @customer.sales.all %>
<p>List of sales made by customer: </p>
<%-# Table showings info on sales by selected customer-%>
<table>
<tbody>
<tr>
	<th> Transaction ID </th>
	<th> Customer Name </th>
	<th> Package ID</th>
</tr>
<%-# interates threw sales array and uses info to populate table-%>
<% @touse.each do |customerSale| %>
<tr>
	<td><%= link_to @customer.sales.find(customerSale).transaction_id, customerSale %></td>
	<td><%= @customer.sales.find(customerSale).customer.name %></td>
	<td><%= link_to @customer.packages.find(  @customer.sales.find(customerSale).package_id ).package_id , package_path( @customer.sales.find(customerSale).package_id ) %></td>
</tr>
<% end %>
</tbody>
</table>
<%-# Table displaying info for all packages bought by customer -%>
<br>
<p>List of packages bought by customer: </p>
<table>
<tbody>
<tr>
	<th> Package ID </th>
	<th> Product In Package </th>
	<th> Package Cost</th>
	<th> Total # of sales of package </th>
</tr>
<%-# Creates array of all packges bought by customer and supresses dupes -%>
<% @touse2 = @customer.packages.all.uniq.pluck(:id) %>
<%-# Interates threw package array and uses info to populate table -%>
<% @touse2.each do |customerPackage| %>
<tr>
	<td><%= link_to @customer.packages.find(customerPackage).package_id, package_path( @customer.packages.find(customerPackage).id ) %></td>
	<td><%= link_to @customer.products.find( @customer.packages.find(customerPackage).product_id ).product_name, product_path( @customer.packages.find(customerPackage).product.id ) %></td>
	<td><%= @customer.packages.find(customerPackage).cost %></td>
	<td><%= @sales.with_package( customerPackage ).count %></td>
</tr>
<% end %>
</tbody>
</table>
<%-# Table displaying all products bought by customer -%>
<br>
<p>List of products bought by customer: </p>
<table>
<tbody>
<tr>
	<th> Product Name </th>
	<th> Product Info </th>
	<th> Product Base Cost</th>
	<th> Total # Of Packages With Product </th>
	<th> Total # Of Sales With Product </th>
</tr>
<%-# Creates array of all packges bought by customer and supresses dupes -%>
<% @touse2 = @customer.products.all.uniq.pluck(:id) %>
<%-# Interates threw product array and uses info to populate table -%>
<% @touse2.each do |customerProduct| %>
<tr>
	<td><%= link_to @customer.products.find(customerProduct).product_name, product_path( @customer.products.find(customerProduct).id ) %></td>
	<td><%= @customer.products.find(customerProduct).product_info %></td>
	<td><%= @customer.products.find(customerProduct).product_base_cost %></td>
	<td><%= @packages.with_product( customerProduct ).count %></td>
	<td>
	<% @totalVar = 0 
 	@packages.with_product(customerProduct).each do |myVar2|
 	@totalVar = @totalVar + @sales.with_package(myVar2).count
 	end %>
 	<%= @totalVar %>
	</td>
</tr>
<% end %>
</tbody>
</table>






<p>TESTING: </p>
<%-# Table showings info on sales by selected customer-%>
<table>
<tbody>
<tr>
	<th> TESTING </th>
	<th> TESTING </th>
	<th> TESTING ID</th>
</tr>
<% @touse5 = @customer.products.all.uniq.pluck(:id) %>
<%-# Interates threw package array and uses info to populate table -%>
<% @touse5.each do |customerPackage| %>
<tr>
	<td><%= @sales.with_package( customerPackage ).count %></td>
	<td><%=  %></td>
	<td> 

<% @totalVar = 0 
 @packages.with_product(customerPackage).each do |myVar2|
 @totalVar = @totalVar + @sales.with_package(myVar2).count  
 end %>
 <%= @totalVar %>

	</td>
</tr>
<% end %>
</tbody>
</table>

<% @touse6 = @customer.products.all.uniq.pluck(:id) %>
<br>
<% @touse6.each do |myVar| %>
<% @totalVar = 0 %>
<br>
<% @packages.with_product(myVar).count %>
<br>
<% @packages.with_product(myVar).each do |myVar2| %>
<br>
<% @sales.with_package(myVar2).count %>
<% @totalVar = @totalVar + @sales.with_package(myVar2).count  %>
<% end %>
<%= @totalVar %>
<% end %>

<br><br>
<% @touse7 = @customer.products.all.uniq.pluck(:id)

@touse7.each do |myVar| 
 @totalVar = 0 

@packages.with_product(myVar).count 

 @packages.with_product(myVar).each do |myVar2| 

 @sales.with_package(myVar2).count 
 @totalVar = @totalVar + @sales.with_package(myVar2).count  
 end 
 @totalVar 
 end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Geting Pinned", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to  about_path do %>
          <span class="glyphicon glyphicon-road"></span> About Us
            <% end %>
        </li>
         <li> <%= link_to  root_path do %>
          <span class="glyphicon glyphicon-home"></span> Home
            <% end %>
         </li>
         <% if user_signed_in? %>
         <li> <%= link_to new_pin_path  do %>
          <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
         </li>
          <li> <%= link_to pins_path  do %>
          <span class="glyphicon glyphicon-pushpin"></span> View Pins
            <% end %>
         </li>
          <li> <%= link_to  edit_user_registration_path do %>
          <span class="glyphicon glyphicon-wrench"></span> Settings
            <% end %>
          </li>
          <li> <%= link_to  destroy_user_session_path, method: :delete do %>
          <span class="glyphicon glyphicon-remove-sign"></span> Log Out
            <% end %>
          </li>
                         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Other Thing <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li> <%= link_to  customers_path do %>
            <span class="glyphicon glyphicon-plane"></span> Customer Info
            <% end %>
            </li>
            <li> <%= link_to  products_path do %>
            <span class="glyphicon glyphicon-plane"></span> Product Info
            <% end %>
            </li>
            <li> <%= link_to  packages_path do %>
            <span class="glyphicon glyphicon-plane"></span> Package Info
            <% end %>
            </li>
            <li> <%= link_to  sales_path do %>
            <span class="glyphicon glyphicon-plane"></span> Sale Info
            <% end %>
          </ul>
        </li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/about.html.erb
<h1>About us</h1?>
</p> We help you get pinned about audio books </p>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
        <%= link_to image_tag(pin.myimage.url(:medium)), pin %>
        <div class="panel-body">
        <%= pin.description %> <br>
        <%= pin.user.name if pin.user %>
        <% if pin.user == current_user %>
        <div class="actions">
          <%= link_to edit_pin_path(pin) do %>
          <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
          <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' }  do %>
          <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
        </div>
      <% end %>
    </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class='row'>
	<div class="col-md-offset-2 col-md-8">
	<div class="panel panel-danger">
	<div class="panel-heading center">
<%= image_tag @pin.myimage.url(:medium) %>
</div>
<div class="panel-body">
<p>
  <%= @pin.description %> <br>
  <%= @pin.user.name if @pin.user %>
</p>
<% if @pin.user == current_user %>
<%= link_to  edit_pin_path(@pin) do %>
<span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
<% end %>
</div>
</div>
</div>

app/views/products/index.html.erb
<h1> Products by name </h1>
<%-# List of products -%>
<ul>
	<% @products.each do |product| %>
	<li><%= link_to product.product_name, product %></li>
	<% end %>
</ul>
<%-# Link to add new product -%>
<%= link_to new_product_path  do %>
<span class="glyphicon glyphicon-plus"></span> New Product
<% end %>
<br><br>
<p>Calculations:</p>
<%-# Calculate and display total # of products -%>
<p> Total # of products: <%= @products.each.count %> </P>
<%-# Calculate and display total # of sales of all products -%>
<% @totalSalesNumber = 0 %>
<% @products.each do |salesVar| %>
<% @totalSalesNumber = @totalSalesNumber + salesVar.sales.count %>
<% end %>
<p> Total # of sales of all products: <%= @totalSalesNumber %> </P>

app/views/products/show.html.erb
<h1> Show page </h1>
<%-# Info on selected product -%>
<table>
<tbody>
<tr>
	<th> Product Name </th>
	<th> Product Info</th>
	<th> Base Cost</th>
</tr>
<tr>
	<td><%= @product.product_name %></td>
	<td><%= @product.product_info %></td>
	<td><%= @product.product_base_cost %></td>
</tr>
</tbody>
</table>
<%-# link back to index page -%>
<%= link_to "All Products", products_path %>
<br><br>
<%-# shows # of pacakges with selected product -%>
<p>Number of packages with this product: <%= @product.packages.count %></p>
<%-# shows # of sales of selected product threw all packages -%>
<p>Number of sales with this product threw all packages: <%= @product.sales.all.count %></p>
<%-# shows # of customers who bought selected product threw all packages -%>
<p>Number of customers who bought this product threw all packages: <%=  @product.customers.all.uniq.pluck(:id).count %></p>
<%-# Array of packages with selected product -%>
<% @touse = @product.packages.all %>
<%-# Table showings info on packages with selected product -%>
<p> List of pacakges with product: </p>
<table>
<tbody>
<tr>
	<th> Package ID </th>
	<th> Product Name </th>
	<th> Package Cost</th>
	<th> Total # of sales of package </th>
</tr>
<%-# interates threw package array and uses info to populate table-%>
<% @touse.each do |productPackage| %>
<tr>
	<td><%= link_to @product.packages.find(productPackage).package_id, productPackage %></td>
	<td><%= @product.packages.find(productPackage).product.product_name %></td>
	<td><%= @product.packages.find(productPackage).cost %></td>
	<td><%= @sales.with_package( productPackage ).count %></td>
</tr>
<% end %>
</tbody>
</table>
<%-# Table displaying info for sales that contained selected prodcut (threw any package) -%>
<br><br>
<p> List of sales with product: </p>
<table>
 <tbody>
<tr>
 <th> Transation ID </th>
 <th> Customer Name </th>
 <th> Package ID</th>
</tr>
<%-# Creates array of all sales that contained selected prodcut (threw any package) -%>
<% @touse2 = @product.sales.all %>
<%-# Interates threw package array and uses info to populate table -%>
<% @touse2.each do |productSale| %>
<tr>
	<td><%= link_to @product.sales.find(productSale).transaction_id, sale_path( @product.sales.find(productSale).id ) %></td>
	<td><%= link_to @product.customers.find( @product.sales.find(productSale).customer_id ).name , customer_path(  @product.sales.find(productSale).customer_id ) %></td>
	<td><%= link_to @product.packages.find( @product.sales.find(productSale).package_id ).package_id , package_path( @product.sales.find(productSale).package_id ) %></td>
</tr>
<% end %>
</tbody>
</table>
<%-# Table displaying all customers who bought this package (threw any package) -%>
<br><br>
<p> List of customers who bought product: </p>
<table>
 <tbody>
<tr>
 <th> Customer Name </th>
 <th> Company Name </th>
 <th> Customer ID</th>
 <th> Total # Of Sales To Customer</th>
</tr>
<%-# Creates array of all customers who bought by product (threw any package) and supresses dupes -%>
<% @touse2 = @product.customers.all.uniq.pluck(:id) %>
<%-# Interates threw customer array and uses info to populate table -%>
<% @touse2.each do |productCustomer| %>
<tr>
	<td><%= link_to @product.customers.find(productCustomer).name, customer_path( @product.customers.find(productCustomer).id ) %></td>
	<td><%= @product.customers.find(productCustomer).company_name %></td>
	<td><%= @product.customers.find(productCustomer).customer_id %></td>
	<td><%= @sales.with_customer( productCustomer ).count %></td>
</tr>
<% end %>
 </tbody>
</table>

app/views/sales/index.html.erb
<h1> Sales by user input transaction ID </h1>
<%-# List of sales -%>
<ul>
	<% @sales.each do |sale| %>
	<li><%= link_to sale.transaction_id, sale %></li>
	<% end %>
</ul>
<%-# Link to add new sale -%>
<%= link_to new_sale_path  do %>
<span class="glyphicon glyphicon-plus"></span> New Sale
<% end %>
<br><br>
<p>Calculations:</p>
<%-# Calculate and display total # of sales -%>
<p> Total # of sales: <%= @sales.each.count %> </P>
<%-# Calculate and display total # of customers who have at least 1 sale -%>
<p> Total # of customers invovled in all sales: <%= @sales.select(:customer_id).distinct.count%> </P>
<%-# Calculate and display total # of packages who have at least 1 sale -%>
<p> Total # of packages invovled in all sales: <%= @sales.select(:package_id).distinct.count%> </P>

app/views/sales/show.html.erb
<h1> Show page </h1>
<%-# Info on selected sale -%>
<table >
<tbody >
<tr>
	<th> Transaction ID </th>
	<th> Customer ID</th>
	<th> Package ID</th>
</tr>
<tr>
	<td><%= @sale.transaction_id %></td>
	<td><%= link_to @sale.customer.name, customer_path( @sale.customer_id ) %></td>
	<td><%= link_to @sale.package.package_id, package_path( @sale.package_id ) %></td>
</tr>
 </tbody>
</table>
<%-# link back to index page -%>
<%= link_to "All Sales", sales_path %>
<%-# More info on customer in selected sale -%>
<br><br>
<p> More info on customer: </p>
<table>
<tbody>
<tr>
	<th> Customer Name </th>
	<th> Company Name </th>
	<th> Customer ID </th>
	<th> Total # Of Sales To Customer</th>
</tr>
<tr>
	<td><%= link_to @sale.customer.name, customer_path( @sale.customer_id ) %></td>
	<td><%= @sale.customer.company_name %></td>
	<td><%= @sale.customer.customer_id %></td>
	<td><%= @sales.with_customer( @sale.customer ).count %></td>
</tr>
</tbody>
</table>
<%-# More info on pacakage in selected sale -%>
<br><br>
<p> More info on package: </p>
<table>
<tbody>
<tr>
	<th> Package ID </th>
	<th> Product Name </th>
	<th> Cost </th>
	<th> Total # of sales of package </th>
</tr>
<tr>
	<td><%= link_to @sale.package.package_id, package_path( @sale.package_id ) %></td>
	<td><%= link_to @sale.package.product.product_name, product_path( @sale.package.product_id ) %></td>
	<td><%= @sale.package.cost %></td>
	<td><%= @sales.with_package( @sale.package_id ).count %></td>
</tr>
</tbody>
</table>
<%-# More info on product in pacakage in selected sale -%>
<br><br>
<p> More info on product in package: </p>
<table>
<tbody>
<tr>
	<th> Product Name </th>
	<th> Product Info </th>
	<th> Base Cost </th>
	<th> Total # Of Packages With Product </th>
	<th> Total # Of Sales With Product </th>
</tr>
<tr>
	<td><%= link_to @sale.package.product.product_name, product_path( @sale.package.product.id ) %></td>
	<td><%= @sale.package.product.product_info %></td>
	<td><%= @sale.package.product.product_base_cost %></td>
	<td><%= @packages.with_product(  @sale.package.product_id ).count %></td>
	<td>
	<% @totalVar = 0 
 	@packages.with_product(@sale.package.product_id).each do |myVar2|
 	@totalVar = @totalVar + @sales.with_package(myVar2).count
 	end %>
 	<%= @totalVar %>
	</td>
</tr>
</tbody>
</table>
<br><br>
<p> All cutomers who bought this package: </p>
<table>
<tbody>
<tr>
	<th> Name </th>
	<th> Company </th>
	<th> Customer ID</th>
	<th> Total # Of Sales To Customer</th>
</tr>
<% @test = @sales.with_package(@sale.package).uniq.pluck(:customer_id) %>
<% @test.each do |testVar| %>
<tr>
	<td><%= link_to @customers.find( testVar ).name, customer_path( @customers.find( testVar ).id )  %></td>
	<td><%=@customers.find( testVar ).company_name  %></td>
	<td><%=@customers.find( testVar ).customer_id %></td>
	<td><%=@sales.with_customer( @customers.find( testVar ).id ).count %></td>
</tr>
<% end %>
</tbody>
</table>
<br><br>
<br><br>
<p> All packages that contain the product in this package: </p>
<table>
<tbody>
<tr>
	<th> Package ID </th>
	<th> Product Name </th>
	<th> Cost </th>
	<th> Total # Of Sales Of Package </th>
</tr>
<% @test = @sales.with_package(@sale.package) %>
<%= @test2 =  @test.all.uniq.pluck(:id) %>
<% @test2.each do |testVar| %>
<tr>

</tr>
<% end %>
</tbody>
</table>
<br><br>
<p> TESTING <p>
<br>


<table>
<tbody>
<tr>
	<th> TESTING </th>
	<th> TESTING </th>
	<th> TESTING ID</th>
</tr>
<% @test = @sales.with_package(@sale.package) %>
<%= @test2  = @test.all.uniq.pluck(:customer_id)%>
<% @test2.each do |testVar| %>
<tr>
	<td><%=@customers.find( testVar ).name  %></td>
	<td><%=@customers.find( testVar ).company_name  %></td>
	<td> 

	<% 

	%>

	</td>
</tr>
<% end %>
</tbody>
</table>

<%=
@sales.with_package(@sale.package).each do |var2Use|
@sale.customer_id

end
%>